apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx-manifests 
    repoURL: https://github.com/patrickkabongo/python-helloworld 
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}